### ISSUE TITLE
Some examples fail

### ISSUE THREAD

**Issue by karstenw** [plotdevice/plotdevice#28]
On osx 10.10.4.

All examples were selected from the menu (btw very inconvenient) of a fresh downloaded app with the libraries installed in ~/Libraries/Application Support/PlotDevice/.

Examples/Interactivity/Avoider:

```
2015-08-10 00:24:58
Traceback (most recent call last):
  File "<Untitled>", line 20, in <module>
    from plotdevice.lib.geometry import angle, coordinates, distance
ImportError: No module named geometry
```

Examples/Advanced/Clipping:

```
Traceback (most recent call last):
  File "<Untitled>", line 49, in <module>
    font("Bodoni", "bold", 72)
DeviceError: ambiguous font family name "Bodoni".
Did you mean: ['Bodoni 72', 'Bodoni Ornaments', 'Bodoni 72 Oldstyle', 'Bodoni 72 Smallcaps']
```

Examples/Text/RandomText:

```
Traceback (most recent call last):
  File "<Untitled>", line 45, in <module>
    text(someText, 0,0)
IndexError: NSRangeException - NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds
```

**Comment by samizdatco** [comment]
fixed in 584adfe2880b856771e16e8127a30440305729de
