### ISSUE TITLE
CoreImage library not working

### ISSUE THREAD

**Issue by clankill3r** [plotdevice/plotdevice#42]
When trying to use to CoreImage library I get the following error:

```
Traceback (most recent call last):
  File "coreimage-example7.py", line 23, in draw
    canvas = coreimage.canvas(WIDTH, HEIGHT)
  File "__init__.py", line 577, in canvas
    from plotdevice.gfx.transform import Dimension
ImportError: No module named transform
```

**Comment by oshabal** [comment]
Same for me...2021. Any luck fixing it? Thanks

**Comment by clankill3r** [comment]
This project is dead for years.
Maybe you can use processing? www.processing.org

**Comment by samizdatco** [comment]
The libraries are quite old at this point and aren't really ready for prime time. CoreImage in particular is *mostly* working but is quite laggy and emits some odd warnings as it runs. Feel free to experiment with it though (and please do submit a pull request if you make any progress with it!): https://github.com/plotdevice/plotdevice-libs/tree/master/coreimage
