### ISSUE TITLE
Cannot build on Ubuntu

### ISSUE THREAD

**Issue by adamurban98** [plotdevice/plotdevice#50]
On `Linux Ubuntu 16.04.5 LTS`
After trying to install with 
`sudo pip3 install plotdevice`
The following error is thrown.
```
 Compiling required c-extensions
    Building pathmatics...
    Traceback (most recent call last):
      File "app/deps/build.py", line 82, in <module>
        build_extensions()
      File "app/deps/build.py", line 48, in build_extensions
        build(lib_name)
      File "app/deps/build.py", line 19, in build
        raise OSError("Could not build %s" % extension)
    OSError: Could not build pathmatics
    error: command '/usr/bin/python3' failed with exit status 1

```
```
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0nouwqob/plotdevice/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4lzesa58/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0nouwqob/plotdevice/
```

**Comment by samizdatco** [comment]
> On `Linux Ubuntu 16.04.5 LTS` After trying to install with `sudo pip3 install plotdevice` The following error is thrown.

PlotDevice uses macOS system frameworks for all of its graphics rendering so it doesn't run on linux, sadly.
